version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    volumes:
      - ./:/flai_rs
    environment:
      - NODE_ENV=development
    command: npm run start -- --host 0.0.0.0 --port 42069
